# frozen_string_literal: true

# Generate docs/api/CHECKLIST.md from the latest contract snapshot, the
# generated operation table and the behaviour tests.
#
# Why: "complete" has to be something CI checks, not something we claim.
# Every column is derived: registered from the operation table, named from
# behaviour tests that name the operationId, live from sandbox evidence
# (none yet). Nothing is ticked by hand, so the checklist cannot lie.
#
# Standard library only. Run it with `bundle exec rake checklist`.

require "json"
require_relative "operation_table"

# Renders the operation checklist.
module Checklist
  class Error < StandardError; end

  PREFIX = "/api/external/v2"
  UNVERIFIED = "unverified: no sandbox access"
  DEPRECATED = "skipped: deprecated"

  # Finds the behaviour tests that name an Operation. A test names one with
  # a comment directly above its method, one operationId per line:
  #
  #   # names: finalizeCustomerInvoice
  #   def test_finalize
  #
  # Only test/resources/ is read, so the contract test can never count.
  module NamedTests
    GLOB = "test/resources/**/*_test.rb"
    MARKER = /\A\s*#\s*names:\s*(\S+)\s*\z/
    COMMENT = /\A\s*#/
    TEST = /\A\s*def\s+(test_\w+)/

    # Returns { operationId => ["test/resources/x_test.rb#test_name", ...] }.
    def self.scan(root:, known:)
      named = Hash.new { |hash, id| hash[id] = [] }
      Dir.glob(GLOB, base: root).sort.each do |file|
        each_marker(File.read(File.join(root, file)), file) do |id, test|
          raise Error, "#{file}: #{id} is not an operationId in the snapshot" unless known.include?(id)

          named[id] << "#{file}##{test}"
        end
      end
      named.to_h
    end

    # Yields [operationId, test name] for each marker. Markers wait in
    # `pending` until the next test method; any other code first is an error.
    def self.each_marker(source, file, &)
      pending = []
      source.each_line.with_index(1) { |line, number| read_line(line, number, pending, file, &) }
      refuse_stray(pending, file)
    end

    def self.read_line(line, number, pending, file)
      if (marker = MARKER.match(line)) then pending << [marker[1], number]
      elsif (test = TEST.match(line)) then pending.shift(pending.size).each { |marked| yield marked.first, test[1] }
      elsif !COMMENT.match?(line) then refuse_stray(pending, file)
      end
    end

    def self.refuse_stray(pending, file)
      return if pending.empty?

      id, number = pending.first
      raise Error, "#{file}:#{number}: \"# names: #{id}\" must sit directly above a test method"
    end
    private_class_method :each_marker, :read_line, :refuse_stray
  end

  def self.render(document, source:, registered:, named:)
    operations = document.fetch("operations")
    registered = registered.to_set
    [
      header(source, document.fetch("retrieved_on")),
      summary(operations, registered, named),
      *groups(operations).map { |group, rows| section(group, rows, registered, named) }
    ].join("\n")
  end

  def self.header(source, date)
    <<~MARKDOWN
      <!--
        Generated by `rake checklist` from #{source},
        lib/pennylane_client/operations.rb and the behaviour tests under test/resources/.
        Do not edit by hand: `rake stale` fails when this file differs from what the generator writes.
      -->

      # Operation checklist

      Contract snapshot of #{date}. One row per Operation, grouped by resource group (Pennylane's tag). Paths are relative to `#{PREFIX}`.

      - **registered**: in the generated operation table, so `client.call` can reach it.
      - **named**: a behaviour test in `test/resources/` names the operationId with `# names: <operationId>` directly above it. The contract test never counts.
      - **live**: `sandbox-verified <date> (by @user)`, `#{UNVERIFIED}`, or `#{DEPRECATED}`.
    MARKDOWN
  end

  def self.summary(operations, registered, named)
    live = operations.reject { _1["deprecated"] }
    <<~MARKDOWN
      | | Operations |
      |---|---|
      | In the snapshot | #{operations.size} |
      | Live (not deprecated) | #{live.size} |
      | Registered | #{operations.count { registered.include?(_1["operation_id"]) }} |
      | Named | #{live.count { named.key?(_1["operation_id"]) }} of #{live.size} live |
      | Live-verified | 0 of #{live.size} live |
    MARKDOWN
  end

  def self.groups(operations)
    operations.group_by { _1.fetch("tags").first || "Untagged" }
              .sort_by { |group, _| [group.downcase, group] }
              .map { |group, rows| [group, rows.sort_by { _1.values_at("path", "method") }] }
  end

  def self.section(group, rows, registered, named)
    live = rows.reject { _1["deprecated"] }
    lines = rows.map { |operation| row(operation, registered, named) }
    <<~MARKDOWN
      ## #{group} (#{live.count { named.key?(_1["operation_id"]) }} of #{live.size} named)

      | operationId | Method | Path | registered | named | live | proven by |
      |---|---|---|---|---|---|---|
      #{lines.join("\n")}
    MARKDOWN
  end

  def self.row(operation, registered, named)
    id = operation.fetch("operation_id")
    tests = named.fetch(id, [])
    cells = [
      "`#{id}`", operation.fetch("method"), "`#{operation.fetch("path").delete_prefix(PREFIX)}`",
      registered.include?(id) ? "yes" : "no", tests.empty? ? "no" : "yes",
      operation["deprecated"] ? DEPRECATED : UNVERIFIED, tests.map { "`#{_1}`" }.join("<br>")
    ]
    "| #{cells.join(" | ")} |"
  end
  private_class_method :header, :summary, :groups, :section, :row

  # Reads the latest snapshot and the behaviour tests under root and returns
  # the checklist.
  def self.generate(root:, registered:)
    snapshot = OperationTable.latest_snapshot(File.join(root, "docs/api/contract"))
    document = JSON.parse(File.read(snapshot))
    known = document.fetch("operations").map { _1["operation_id"] }
    render(document, source: snapshot.delete_prefix("#{root}/"),
                     registered: registered, named: NamedTests.scan(root: root, known: known))
  end
end

if $PROGRAM_NAME == __FILE__
  require_relative "../lib/pennylane_client"

  root = File.expand_path("..", __dir__)
  target = File.join(root, "docs/api/CHECKLIST.md")
  File.write(target, Checklist.generate(root: root, registered: PennylaneClient::OPERATIONS.map { _1.id.to_s }))
  puts "Wrote #{target}"
end
