# frozen_string_literal: true

# Read the sandbox reports `rake smoke` writes, and keep the README's
# live-verified count in step with them.
#
# Why: the checklist's live column and the README count must come from
# evidence a contributor committed, never from someone typing a number.
#
# Standard library only. Used by tools/checklist.rb and tools/stale.rb.

require "json"

module Checklist
  class Error < StandardError; end

  # Reads the sandbox reports under docs/api/live/. A report is JSON:
  #
  #   {"format": 1, "verified_on": "2026-10-01", "by": "octocat",
  #    "operations": {"getMe": "pass", "getJournals": "fail: 403 ..."},
  #    "checks": {"webhook_signature": "pass"}}
  #
  # Reports are read oldest first, so for each operation the latest report
  # that ran it decides: "pass" verifies it, anything else leaves it
  # unverified. A check keeps its latest result other than "not run".
  module LiveReports
    DIR = "docs/api/live"
    GLOB = "#{DIR}/*.json".freeze
    FORMAT = 1
    DATE = /\A\d{4}-\d{2}-\d{2}\z/
    # A GitHub username.
    USER = /\A[A-Za-z0-9][A-Za-z0-9-]{0,38}\z/
    PASS = "pass"
    NOT_RUN = "not run"

    # verified: { operationId => [date, user] }
    # checks:   { check => [result, date, user] }
    Live = Data.define(:verified, :checks)
    NONE = Live.new(verified: {}.freeze, checks: {}.freeze)

    def self.scan(root:, known:)
      reports = Dir.glob(GLOB, base: root).map { |file| read(File.join(root, file), file, known) }
      reports.sort_by { [_1.fetch("verified_on"), _1.fetch("file")] }
             .each_with_object(Live.new(verified: {}, checks: {})) { |report, live| apply(report, live) }
    end

    def self.read(path, file, known)
      report = JSON.parse(File.read(path))
      validate(report, file)
      unknown = report.fetch("operations").keys - known
      raise Error, "#{file}: #{unknown.join(", ")} not an operationId in the snapshot" if unknown.any?

      report.merge("file" => file)
    rescue JSON::ParserError, KeyError, NoMethodError => e
      raise Error, "#{file}: not a sandbox report (#{e.message})"
    end

    def self.validate(report, file)
      raise Error, "#{file}: format must be #{FORMAT}" unless report["format"] == FORMAT
      raise Error, "#{file}: verified_on must be YYYY-MM-DD" unless DATE.match?(report["verified_on"].to_s)
      raise Error, "#{file}: by must be a GitHub username" unless USER.match?(report["by"].to_s)
    end

    def self.apply(report, live)
      stamp = report.values_at("verified_on", "by")
      report.fetch("operations").each do |id, result|
        result == PASS ? live.verified[id] = stamp : live.verified.delete(id)
      end
      report.fetch("checks", {}).each do |check, result|
        live.checks[check] = [result, *stamp] unless result == NOT_RUN
      end
    end
    private_class_method :read, :validate, :apply
  end

  # Keeps the README's live-verified count generated, not typed. Only the
  # text between the two markers is rewritten.
  module Readme
    PATH = "README.md"
    START = "<!-- live-count: generated by `rake checklist`, do not edit -->"
    FINISH = "<!-- /live-count -->"
    REGION = /^#{Regexp.escape(START)}\n.*?^#{Regexp.escape(FINISH)}$/m

    def self.update(text, verified:, live:)
      raise Error, "#{PATH} has no #{START} ... #{FINISH} region" unless REGION.match?(text)

      text.sub(REGION) { "#{START}\n#{line(verified, live)}\n#{FINISH}" }
    end

    def self.line(verified, live)
      "Live-verified against a Pennylane sandbox: **#{verified} of #{live}** live operations. " \
        "The [checklist](docs/api/CHECKLIST.md) lists which, and " \
        "[CONTRIBUTING.md](CONTRIBUTING.md#verifying-against-a-real-pennylane-sandbox) says how to add to it."
    end
    private_class_method :line
  end
end
