# frozen_string_literal: true

# Generate lib/pennylane_client/operations.rb from the latest contract
# snapshot.
#
# Why: every Operation in the snapshot must be Registered (reachable through
# `client.call`) without anyone typing a row. The table is plain data, one
# line per operationId, sorted, so a snapshot change shows up as one-line
# diffs. The generator refuses shapes it does not understand rather than
# guessing, because a wrong row fails at request time, far from the cause.
#
# Standard library only. Run it with `bundle exec rake contract:sync`.

require "json"
require_relative "../lib/pennylane_client/operation"

# Turns a contract snapshot into the frozen operation table.
module OperationTable
  class Error < StandardError; end

  BODY_KINDS = {
    "application/json" => :json,
    "multipart/form-data" => :multipart
  }.freeze

  SNAPSHOT_DIR = /\A\d{4}-\d{2}-\d{2}\z/

  # The operations.json of the newest dated folder under root.
  def self.latest_snapshot(root)
    dates = Dir.children(root).grep(SNAPSHOT_DIR).select { File.file?(File.join(root, _1, "operations.json")) }
    raise Error, "no contract snapshot under #{root}" if dates.empty?

    File.join(root, dates.max, "operations.json")
  end

  # One Operation per snapshot record, sorted by operationId bytes.
  def self.rows(document)
    document.fetch("operations").map { |record| row(record) }.sort_by { _1.id.to_s }
  end

  def self.row(record)
    id = record.fetch("operation_id")
    max_limit = max_limit(id, record.fetch("parameters"))
    PennylaneClient::Operation.new(
      id: id.to_sym, verb: record.fetch("method").downcase.to_sym, path: record.fetch("path"),
      paginated: !max_limit.nil?, max_limit:,
      body: body_kind(id, record["request_body"]),
      success: success_code(id, record.fetch("responses")),
      deprecated: record.fetch("deprecated")
    )
  end

  def self.query_parameter(parameters, name)
    parameters.find { _1["in"] == "query" && _1["name"] == name }
  end

  # An operation is paginated when it takes a cursor in the query. The
  # Paginator asks for the largest page, so a paginated operation must
  # document one. Nil when the operation is not paginated.
  def self.max_limit(id, parameters)
    return unless query_parameter(parameters, "cursor")

    maximum = query_parameter(parameters, "limit")&.dig("schema", "maximum")
    raise Error, "#{id}: paginated, but its limit parameter has no maximum" unless maximum.is_a?(Integer)

    maximum
  end

  def self.body_kind(id, request_body)
    return if request_body.nil?

    types = request_body.fetch("content").keys
    raise Error, "#{id}: expected one request content type, got #{types.join(", ")}" unless types.one?

    BODY_KINDS.fetch(types.first) { raise Error, "#{id}: unknown request content type #{types.first}" }
  end

  def self.success_code(id, responses)
    codes = responses.keys.grep(/\A2\d\d\z/)
    raise Error, "#{id}: expected one 2xx response, got #{codes.inspect}" unless codes.one?

    Integer(codes.first)
  end
  private_class_method :row, :query_parameter, :max_limit, :body_kind, :success_code

  # The Ruby source of one row, on one line.
  def self.literal(row)
    fields = row.to_h.map { |name, value| "#{name}: #{value.inspect}" }
    "Operation.new(#{fields.join(", ")})"
  end

  def self.render(rows, source:)
    lines = rows.sort_by { _1.id.to_s }.map { |row| "    #{literal(row)}" }
    <<~RUBY
      # frozen_string_literal: true

      # Generated by `rake contract:sync` from #{source}.
      # Do not edit by hand: `rake stale` fails when this file differs from
      # what the generator writes.

      module PennylaneClient
        # Every Operation in the contract snapshot, sorted by operationId.
        #
        # @api private
        OPERATIONS = [
      #{lines.join(",\n")}
        ].freeze
      end
    RUBY
  end

  # Reads the latest snapshot under contract_root and returns the table source.
  def self.generate(contract_root:, relative_to:)
    snapshot = latest_snapshot(contract_root)
    source = snapshot.delete_prefix("#{relative_to}/")
    render(rows(JSON.parse(File.read(snapshot))), source: source)
  end
end

if $PROGRAM_NAME == __FILE__
  root = File.expand_path("..", __dir__)
  target = File.join(root, "lib/pennylane_client/operations.rb")
  File.write(target, OperationTable.generate(contract_root: File.join(root, "docs/api/contract"), relative_to: root))
  puts "Wrote #{target}"
end
