module PennylaneClient
  def self.new: (token: token, ?base_url: String, ?transport: _Transport, ?logger: untyped,
                 ?on_request: (^(Instrumentation::event) -> void)?, ?limiters: _LimiterRegistry,
                 ?max_retry_wait: Numeric) -> Client

  class Client
    DEFAULT_BASE_URL: String
    RETRY_POLICIES: Hash[Symbol?, :default | :always]

    def initialize: (token: token, ?base_url: String, ?transport: _Transport, ?logger: untyped,
                     ?on_request: (^(Instrumentation::event) -> void)?, ?limiters: _LimiterRegistry,
                     ?max_retry_wait: Numeric) -> void

    def call: (Symbol | String operation_id, ?untyped body, **untyped params) -> untyped

    def paginate: (Symbol | String operation_id, **untyped params) -> Enumerator::Lazy[Hash[Symbol, untyped], void]

    def pages: (Symbol | String operation_id, **untyped params) -> Enumerator::Lazy[Hash[Symbol, untyped], void]

    def customer_invoices: () -> Resources::CustomerInvoices

    def customers: () -> Resources::Customers

    def supplier_invoices: () -> Resources::SupplierInvoices

    def suppliers: () -> Resources::Suppliers

    def sepa_mandates: () -> Resources::SepaMandates

    def gocardless_mandates: () -> Resources::GocardlessMandates

    def pro_account_mandates: () -> Resources::ProAccountMandates

    def bank_accounts: () -> Resources::BankAccounts

    def bank_establishments: () -> Resources::BankEstablishments

    def transactions: () -> Resources::Transactions

    def quotes: () -> Resources::Quotes

    def inspect: () -> String

    private

    @customer_invoices: Resources::CustomerInvoices?

    @customers: Resources::Customers?

    @supplier_invoices: Resources::SupplierInvoices?

    @suppliers: Resources::Suppliers?

    @sepa_mandates: Resources::SepaMandates?

    @gocardless_mandates: Resources::GocardlessMandates?

    @pro_account_mandates: Resources::ProAccountMandates?

    @bank_accounts: Resources::BankAccounts?

    @bank_establishments: Resources::BankEstablishments?

    @transactions: Resources::Transactions?

    @quotes: Resources::Quotes?

    def paginator: (Symbol | String operation_id, Hash[Symbol, untyped] params) -> Paginator
  end
end
