module PennylaneClient
  module Resources
    type item = Hash[Symbol, untyped]
    type result = Hash[Symbol, untyped] | bool
    # What Multipart streams as a file part.
    type file = File | IO | StringIO | Pathname | Upload

    class Resource
      @client: Client

      def initialize: (Client client) -> void

      def inspect: () -> String

      private

      def call: (Symbol operation_id, ?untyped body, **untyped params) -> untyped

      def paginate: (Symbol operation_id, **untyped params) -> Enumerator::Lazy[item, void]
    end

    class CustomerInvoices < Resource
      def list: (**untyped params) -> Enumerator::Lazy[item, void]

      def find: (Integer id) -> item

      def create: (**untyped attributes) -> item

      def update: (Integer id, **untyped attributes) -> item

      def delete: (Integer id) -> result

      def create_from_quote: (**untyped attributes) -> item

      def import: (**untyped attributes) -> item

      def import_e_invoice: (file file, **untyped fields) -> item

      def finalize: (Integer id) -> item

      def mark_as_paid: (Integer id) -> result

      def mark_installment_as_paid: (Integer customer_invoice_id, Integer id) -> result

      def send_by_email: (Integer id, **untyped fields) -> result

      def send_to_pa: (Integer id) -> result

      def link_credit_note: (Integer id, credit_note_id: Integer) -> item

      def match_transaction: (Integer customer_invoice_id, transaction_id: Integer) -> result

      def unmatch_transaction: (Integer customer_invoice_id, Integer transaction_id) -> result

      def update_imported: (Integer id, **untyped attributes) -> item

      def invoice_lines: (Integer customer_invoice_id, **untyped params) -> Enumerator::Lazy[item, void]

      def invoice_line_sections: (Integer customer_invoice_id, **untyped params) -> Enumerator::Lazy[item, void]

      def payments: (Integer customer_invoice_id, **untyped params) -> Enumerator::Lazy[item, void]

      def matched_transactions: (Integer customer_invoice_id, **untyped params) -> Enumerator::Lazy[item, void]

      def custom_header_fields: (Integer customer_invoice_id, **untyped params) -> Enumerator::Lazy[item, void]

      def appendices: (Integer customer_invoice_id, **untyped params) -> Enumerator::Lazy[item, void]

      def upload_appendix: (Integer customer_invoice_id, file file) -> item

      def categories: (Integer customer_invoice_id, **untyped params) -> Enumerator::Lazy[item, void]

      def categorize: (Integer customer_invoice_id, Array[{ id: Integer, weight: untyped }] categories) -> Array[item]
    end

    class Customers < Resource
      def list: (**untyped params) -> Enumerator::Lazy[item, void]

      def find: (Integer id) -> item

      def create: (customer_type: "company" | "individual", **untyped attributes) -> item

      def create_company: (**untyped attributes) -> item

      def find_company: (Integer id) -> item

      def update_company: (Integer id, **untyped attributes) -> item

      def create_individual: (**untyped attributes) -> item

      def find_individual: (Integer id) -> item

      def update_individual: (Integer id, **untyped attributes) -> item

      def contacts: (Integer customer_id, **untyped params) -> Enumerator::Lazy[item, void]

      def find_contact: (Integer customer_id, Integer id) -> item

      def create_contact: (Integer customer_id, **untyped attributes) -> item

      def update_contact: (Integer customer_id, Integer id, **untyped attributes) -> item

      def delete_contact: (Integer customer_id, Integer id) -> result

      def categories: (Integer customer_id, **untyped params) -> Enumerator::Lazy[item, void]

      def categorize: (Integer customer_id, Array[{ id: Integer, weight: untyped }] categories) -> Array[item]
    end

    class SupplierInvoices < Resource
      def list: (**untyped params) -> Enumerator::Lazy[item, void]

      def find: (Integer id) -> item

      def import: (**untyped attributes) -> item

      def import_e_invoice: (file file, **untyped fields) -> item

      def update: (Integer id, **untyped attributes) -> item

      def validate_accounting: (Integer id) -> item

      def update_payment_status: (Integer supplier_invoice_id, payment_status: "paid" | "to_be_paid") -> result

      def update_e_invoice_status: (Integer supplier_invoice_id, status: "disputed" | "refused" | "approved", **untyped fields) -> item

      def link_purchase_request: (Integer supplier_invoice_id, purchase_request_id: Integer) -> result

      def match_transaction: (Integer supplier_invoice_id, transaction_id: Integer) -> result

      def unmatch_transaction: (Integer supplier_invoice_id, Integer transaction_id) -> result

      def invoice_lines: (Integer supplier_invoice_id, **untyped params) -> Enumerator::Lazy[item, void]

      def payments: (Integer supplier_invoice_id, **untyped params) -> Enumerator::Lazy[item, void]

      def matched_transactions: (Integer supplier_invoice_id, **untyped params) -> Enumerator::Lazy[item, void]

      def categories: (Integer supplier_invoice_id, **untyped params) -> Enumerator::Lazy[item, void]

      def categorize: (Integer supplier_invoice_id, Array[{ id: Integer, weight: untyped }] categories) -> Array[item]
    end

    class Suppliers < Resource
      def list: (**untyped params) -> Enumerator::Lazy[item, void]

      def find: (Integer id) -> item

      def create: (**untyped attributes) -> item

      def update: (Integer id, **untyped attributes) -> item

      def categories: (Integer supplier_id, **untyped params) -> Enumerator::Lazy[item, void]

      def categorize: (Integer supplier_id, Array[{ id: Integer, weight: untyped }] categories) -> Array[item]
    end

    class SepaMandates < Resource
      def list: (**untyped params) -> Enumerator::Lazy[item, void]

      def find: (Integer id) -> item

      def create: (**untyped attributes) -> item

      def update: (Integer id, **untyped attributes) -> item

      def delete: (Integer id) -> result
    end

    class GocardlessMandates < Resource
      def list: (**untyped params) -> Enumerator::Lazy[item, void]

      def find: (Integer id) -> item

      def send_request: (customer_id: Integer, email: { recipients: Array[String], ?subject: String?, ?body: String? }) -> result

      def associate: (Integer gocardless_mandate_id, customer_id: Integer) -> result

      def cancel: (Integer gocardless_mandate_id) -> result
    end

    class ProAccountMandates < Resource
      def list: (**untyped params) -> Enumerator::Lazy[item, void]

      def send_request: (customer_id: Integer) -> result

      def migration_candidates: (**untyped params) -> Enumerator::Lazy[item, void]

      def migrate: (mandate_type: "SepaMandate" | "Mandate", mandate_id: Integer, **untyped fields) -> item
    end

    class BankAccounts < Resource
      def list: (**untyped params) -> Enumerator::Lazy[item, void]

      def find: (Integer id) -> item

      def create: (**untyped attributes) -> item
    end

    class BankEstablishments < Resource
      def list: (**untyped params) -> Enumerator::Lazy[item, void]
    end

    class Transactions < Resource
      def list: (**untyped params) -> Enumerator::Lazy[item, void]

      def find: (Integer id) -> item

      def create: (**untyped attributes) -> item

      def update: (Integer id, **untyped attributes) -> item

      def categories: (Integer transaction_id, **untyped params) -> Enumerator::Lazy[item, void]

      def categorize: (Integer transaction_id, Array[{ id: Integer, weight: untyped }] categories) -> Array[item]

      def matched_invoices: (Integer transaction_id, **untyped params) -> Enumerator::Lazy[item, void]
    end

    class Quotes < Resource
      def list: (**untyped params) -> Enumerator::Lazy[item, void]

      def find: (Integer id) -> item

      def create: (**untyped attributes) -> item

      def update: (Integer id, **untyped attributes) -> item

      def send_by_email: (Integer id, **untyped fields) -> result

      def update_status: (Integer id, status: "pending" | "accepted" | "denied" | "invoiced" | "expired") -> item

      def invoice_lines: (Integer quote_id, **untyped params) -> Enumerator::Lazy[item, void]

      def invoice_line_sections: (Integer quote_id, **untyped params) -> Enumerator::Lazy[item, void]

      def appendices: (Integer quote_id, **untyped params) -> Enumerator::Lazy[item, void]

      def upload_appendix: (Integer quote_id, file file) -> item
    end

    class CommercialDocuments < Resource
      def list: (**untyped params) -> Enumerator::Lazy[item, void]

      def find: (Integer id) -> item

      def create: (**untyped attributes) -> item

      def update: (Integer id, **untyped attributes) -> item

      def invoice_lines: (Integer commercial_document_id, **untyped params) -> Enumerator::Lazy[item, void]

      def invoice_line_sections: (Integer commercial_document_id, **untyped params) -> Enumerator::Lazy[item, void]

      def appendices: (Integer commercial_document_id, **untyped params) -> Enumerator::Lazy[item, void]

      def upload_appendix: (Integer commercial_document_id, file file) -> item
    end

    class CustomerInvoiceTemplates < Resource
      def list: (**untyped params) -> Enumerator::Lazy[item, void]
    end

    class Numberings < Resource
      def list: (**untyped params) -> Enumerator::Lazy[item, void]
    end
  end
end
